version: '3'
services:
  elasticsearch:
    image: blacktop/elasticsearch:7.0
    ports:
      - "9200:9200"
    networks:
      - elastinet

  kibana:
    depends_on:
      - elasticsearch
    image: blacktop/kibana:7.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elastinet

  filebeat:
    depends_on:
      - kibana
    image: blacktop/filebeat:7.0.0
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./pcap:/pcap
    command: -e
    networks:
      - elastinet

  zeek:
    depends_on:
      - filebeat
    build: ./elastic
    image: blacktop/zeek:elastic
    volumes:
      - ./pcap:/pcap
    cap_add:
      - NET_RAW
    network_mode: "host"
    command: -i af_packet::eth0 local

networks:
  elastinet: